out_dir : 'C:\HERD folder\data\output'

tod_def :
  'Early AM' : [3, 4, 5]
  'AM Peak' : [6, 7, 8]
  'Midday' : [9, 10, 11, 12, 13, 14]
  'PM Peak' : [15, 16, 17, 18]
  'Late Night' : [19, 20, 21, 22]
  'Owl' : [23, 0, 1, 2]

similar_dow :
  0 : [3, 4] # Monday similar days: {Thursday, Friday}
  1 : [2]
  2 : [1]
  3 : [0, 4]
  4 : [0, 3]
  5 : [6]
  6 : [5]